### PR TITLE
Fixes Issue #47 and District Match Problems

### LINKED ISSUE #47: District match zip code input is covered by keyboard with no way to dismiss
image

### PR DESCRIPTION
**Pull request by marcaaron**
- Certain instances of a badly parsed zipcode were causing a continual return the user to input screen. Now the district match screen will send them straight to address for clarification.
- Also fixes #47

### CODE REVIEW

File: src/util/functions.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import distanceInWordsStrict from 'date-fns/distance_in_words_strict';
-const CIVIC_API_KEY = process.env.REACT_NATIVE_API_KEY;
+const REACT_NATIVE_API_KEY = process.env.REACT_NATIVE_API_KEY;
```
Comment (gmferland) [inline src/util/functions.js:2]: If you were having problems with the district match I think making a different alias for the api key is unlikely to solve that

**Review by gmferland — CHANGES_REQUESTED** [review]
Could you adjust the navigation on the survey (`src/screens/Survey/Question.js#41) so that it goes to district match instead of straight to Elections when you finish?

Also, could you make the email/password input on the CredentialInputScreen a KeyboardAvoidingView as well?

File: src/util/functions.js (hunk 1 above)
Comment (marcaaron) [reply src/util/functions.js:2]: Haha. My issue turned out not to be related to API keys.
This name change was more for consistency since there should be no CIVIC_API_KEY in the .env files and REACT_NATIVE_API_KEY is the google key that Google Civic and any other APIs can use AFAIK

**Comment by marcaaron** [comment]
@gmferland Ok fixed! Can we please move your concern about CredentialsInputScreen to the related pull request? The other one with all the bugs you found touches those particular files so I'll just consolidate this there.

File: src/screens/DistrictMatch/fetchDistrict.js [hunk 2]
```diff
@@ -19,9 +19,10 @@ export default async function(){
       }else{
         const officeName = resultJson.offices[0].name.split(' ');
         const district = officeName[officeName.length-1];
-        this.setState({district, view:'DISTRICT_FOUND'}, () => {
-          this.setState({isLoading: false});
-        });
+        /**
+         * Do something with the district here then navigate to main App...
```
Comment (gmferland) [inline src/screens/DistrictMatch/fetchDistrict.js:23]: Yes please save the district in redux and Firebase!!

Comment (marcaaron) [reply src/screens/DistrictMatch/fetchDistrict.js:23]: I would prefer to merge this and have that work exist on a separate branch.

**Comment by gmferland** [comment]
That's fair. Just getting the district match to work correctly is pretty
high priority even if there are downstream errors to fix

**Review by crieggalder — APPROVED** [review]

**Review by gmferland — APPROVED** [review]
